# suppress inspection "SpellCheckingInspection" for whole file
x402.facilitator.private-key=0xc1f97668293dcaecb72bfc6fba31a39d34a1a5d1d3d36e30f237a9cbcb3077e9
x402.examples.nonce=nonce002
#
# Using Liquibase to import test data ==================================================================================
spring.liquibase.enabled=true
spring.liquibase.change-log=db/changelog/dev/dev-data.yaml
#
# Disable cache during local dev =======================================================================================
spring.thymeleaf.cache=false
spring.web.resources.chain.cache=false