name: Deploy docker latest image to Docker Hub

on:
  push:
    branches:
      - development

jobs:

  snapshot:
    name: Deploy docker latest image to Docker Hub
    runs-on: ubuntu-latest
    steps:

      - name: Retrieve the sources
        uses: actions/checkout@v4

      - name: Set up environment
        uses: ./.github/actions/setup

      - name: Build image and run tests
        run: |
          just build_docker_image

      - name: Docker Hub login
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.FACILITATOR_DOCKER_HUB_USERNAME }}
          password: ${{ secrets.FACILITATOR_DOCKER_HUB_PASSWORD }}

      - name: Push docker image to Docker hub
        run: |
          docker push mogamitech/facilitator:latest